services:
  - type: web
    name: ctfd
    env: docker
    plan: free
    repo: https://github.com/snehabiju8/CTFd
    branch: master
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
